const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const compiled = ts.transpileModule(fs.readFileSync(require('node:path').join(__dirname, '../lib/utils/charge-payments.ts'), 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
const output = {};
new Function('exports', compiled)(output);
const { reconcileChargePayments } = output;
const charge = { id: 'exam', school_id: 'school', student_id: 'child', charge_name: 'Exam', amount: 300, paid_amount: 0, remaining_amount: 300, status: 'pending' };
const receipt = { id: 'receipt', school_id: 'school', student_id: 'child', amount_paid: 300, items: [{ item_type: 'exam', item_reference_id: 'exam', amount: 300 }] };
const resolve = (receipts, charges = [charge]) => reconcileChargePayments(charges, receipts)[0];
assert.equal(resolve([receipt]).remaining_amount, 0);
assert.equal(resolve([receipt]).status, 'paid');
assert.equal(resolve([{ ...receipt, amount_paid: 100 }]).remaining_amount, 200);
assert.equal(resolve([receipt, receipt]).paid_amount, 300);
assert.equal(resolve([{ ...receipt, amount_paid: 100 }, { ...receipt, amount_paid: 100 }]).paid_amount, 100);
assert.equal(resolve([receipt], [{ ...charge, paid_amount: 300 }]).paid_amount, 300);
assert.equal(resolve([{ ...receipt, student_id: 'other' }]).paid_amount, 0);
assert.equal(resolve([{ ...receipt, school_id: 'other' }]).paid_amount, 0);
assert.equal(resolve([{ ...receipt, is_reversed: true }]).paid_amount, 0);
assert.equal(resolve([{ ...receipt, amount_paid: 2100, items: [{ item_type: 'tuition', amount: 2000 }, ...receipt.items] }]).paid_amount, 100);
assert.equal(resolve([{ ...receipt, amount_paid: 999 }]).paid_amount, 300);
assert.equal(resolve([{ ...receipt, items: [] }]).paid_amount, 0);
assert.equal(resolve([receipt], [{ ...charge, status: 'waived' }]).status, 'waived');
assert.equal(resolve([{ ...receipt, amount_paid: 100 }, { ...receipt, id: 'second', amount_paid: 100 }]).paid_amount, 200);
assert.equal(resolve([{ ...receipt, amount_paid: 2100, items: [...receipt.items, { item_type: 'tuition', amount: 2000 }] }]).paid_amount, 100);
assert.equal(resolve([{ ...receipt, amount_paid: 0.1, items: [{ ...receipt.items[0], amount: 0.3 }] }, { ...receipt, id: 'fraction', amount_paid: 0.2, items: [{ ...receipt.items[0], amount: 0.2 }] }], [{ ...charge, amount: 0.3 }]).remaining_amount, 0);
console.log('Charge payment regression checks passed');
